// <auto-generated />
using System;
using DailyTool.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DailyTool.Migrations
{
    [DbContext(typeof(CodeDbContext))]
    partial class CodeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DailyTool.Models.Plans", b =>
                {
                    b.Property<Guid>("PlanId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Create_At");

                    b.Property<string>("Description");

                    b.Property<float>("FinishRate");

                    b.Property<string>("Title");

                    b.HasKey("PlanId");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("DailyTool.Models.Report_Plan", b =>
                {
                    b.Property<Guid>("Report_Plane_Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("FinishDate");

                    b.Property<Guid>("PlandId");

                    b.Property<Guid>("ReportId");

                    b.HasKey("Report_Plane_Id");

                    b.ToTable("Report_Plan");
                });

            modelBuilder.Entity("DailyTool.Models.ReportItems", b =>
                {
                    b.Property<Guid>("ReportId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created_At");

                    b.Property<string>("Du_dinh");

                    b.Property<bool>("IsFinish");

                    b.Property<string>("Issue");

                    b.Property<string>("Ke_hoach");

                    b.Property<string>("Title");

                    b.HasKey("ReportId");

                    b.ToTable("ReportItems");
                });

            modelBuilder.Entity("DailyTool.Models.Roles", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("RoleName");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("DailyTool.Models.User_Reports", b =>
                {
                    b.Property<Guid>("User_Report_Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ReportId");

                    b.Property<Guid>("UserId");

                    b.HasKey("User_Report_Id");

                    b.ToTable("User_Reports");
                });

            modelBuilder.Entity("DailyTool.Models.Users", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Create_At");

                    b.Property<string>("Email");

                    b.Property<string>("PassWord");

                    b.Property<Guid>("ReportReceiver");

                    b.Property<int>("RoleId");

                    b.Property<string>("UserName");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
